[[architecture]]
  name = "00.架构师知识体系"
  identifier = "00.knowledge-system"
  url = "/architecture/00.knowledge-system/"
  weight = 1001

[[architecture]]
  name = "01.分析与设计"
  identifier = "01.design-method"
  url = "/architecture/01.design-method/"
  weight = 1002

[[architecture]]
  name = "02.分析与设计"
  identifier = "02.analysis-and-design"
  url = "/architecture/02.analysis-and-design/"
  weight = 1003

[[architecture]]
  name = "03.架构模式"
  identifier = "03.architectural-pattern"
  url = "/architecture/03.architectural-pattern/"
  weight = 1004

[[architecture]]
  name = "03.架构评估"
  identifier = "04.architecture-evaluation"
  url = "/architecture/04.architecture-evaluation/"
  weight = 1004

[[main]]
  name = "架构设计"
  identifier = "architecture"
  url = "/architecture/directory"
  weight = 10

[[microservice]]
  name = "01. 微服务方法论"
  weight = 2010
  identifier = "01.methodology"
  url = "/microservice/01.methodology/"

[[microservice]]
  name = "02. 微服务管理"
  weight = 2020
  identifier = "02.management"
  url = "/microservice/02.management/"

[[microservice]]
  name = "03. 存储技术"
  weight = 2030
  identifier = "03.storage"
  url = "/microservice/03.storage/"

[[microservice]]
  name = "04. 业务支持"
  weight = 2040
  identifier = "04.business-support"
  url = "/microservice/04.business-support/"

[[microservice]]
  name = "05. DevOps"
  weight = 2050
  identifier = "05.devops"
  url = "/microservice/05.devops/"

[[microservice]]
  name = "06. 新技术"
  weight = 2060
  identifier = "06.new-technology"
  url = "/microservice/06.new-technology/"

[[main]]
  name = "微服务实践"
  identifier = "microservice"
  url = "/microservice/directory"
  weight = 20

[[main]]
  name = "DevOps实践"
  weight = 30
  url = "/devops/"

[[main]]
  name = "过程管理"
  weight = 40
  url = "/docs/prologue/introduction/"

[[main]]
  name = "IoT技术"
  weight = 50
  url = "/docs/prologue/introduction/"

[[main]]
  name = "随笔"
  weight = 60
  url = "/docs/prologue/introduction/"

[[social]]
  name = "GitHub"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-github\"><path d=\"M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22\"></path></svg>"
  url = "https://github.com/guowei1651"
  post = "v0.1.0"
  weight = 10

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/waleskuo"
  weight = 20

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
